version: '3.8'
services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
  app:
    build: .
    ports:
      - '3500:3500'
    environment:
      - MONGO_URL=mongodb://mongo:27017/backend3
    depends_on:
      - mongo
